### ISSUE TITLE
Troubleshooting Help

### ISSUE THREAD

**Issue by 53845714nF** [mathoudebine/homeassistant-timebox-mini#11]
Hello,
I use a tp-link UB400 Stick (Bluetooth 4.0 Nano USB Adapter) and I have a virtual machine of Home assistant on my Proxmox Host.

On my Proxmox I see the Stick:
```
lsusb
Bus 001 Device 056: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
```
On my Home Assistant I also see the device:
```
lsusb
Bus 009 Device 002: ID 0a12:0001
```

I install the service with Hacs, as in the instructions.
Then I try to use the service with this:
```
service: timebox_mini.action
data:
  mac_addr: 00:1A:7D:DA:71:15
  action: animation
  image: hourglass_black
```

And I also added '' around the Mac address:
```
service: timebox_mini.action
data:
  mac_addr: '00:1A:7D:DA:71:15'
  action: animation
  image: hourglass_black
```
But I get this error any time:
```
Error calling the service timebox_mini.action. Unknown error
```

On the  Home Assistant Shell I dont have `apt` or `hcitool`:
```
[core-ssh timebox_mini]$ hcitool
-bash: hcitool: command not found
[core-ssh timebox_mini]$ apt
-bash: apt: command not found
```
Do you have any idea how I could debug this further?
